Hash link converter and `/embed` and `/postembed` refactor
destinygg/chat-gui pull request #152
Opened 2023-02-14 20:50 UTC by Fritz-02

Added a HashLinkConverter class to handle converting URLs to an embed hash link.
Refactored `/embed` and `/postembed` commands to use this class. (#149)

2023-02-14 22:53 UTC, 11k requested changes

2023-02-14 22:53 UTC, 11k commented on assets/chat/js/hashlinkconverter.test.js
> +    }
I think using `toThrow()` is a better approach here. It checks to see if the thrown error message contains the expected error message.
```suggestion
    expect(() => hlc.convert(url)).toThrow(expectedError);
```

2023-02-14 22:53 UTC, 11k commented on assets/chat/js/hashlinkconverter.test.js
> +};
Considering what you're actually testing is if the correct error is thrown for each invalid link, maybe it's better to define/export these error messages in `hashlinkconvertor.js`? You can then use them here without having to redefine.

2023-02-14 22:53 UTC, 11k commented on assets/chat/js/chat.js
>    cmdEMBED(parts) {
I think having separate error messages related to the number of arguments is unnecessary. Try to simplify all this such that you just print two things on invalid use of the command: the error from the convertor, and a usage hint.

2023-02-15 14:37 UTC, Fritz-02 commented
Error outputs for the commands, to show what they look like. The info message about usage for `/postembed` might be too lengthy, so it could be split across two messages.

![Screenshot from 2023-02-15 05-29-09](https://user-images.githubusercontent.com/78668750/219056256-b8f2dab7-0c36-4fe7-9884-2dcf8e1dec53.png)
![Screenshot from 2023-02-15 05-47-08](https://user-images.githubusercontent.com/78668750/219056262-327afda3-4556-49f4-89f8-ae36396cfad5.png)

2023-02-15 20:10 UTC, 11k commented
The usage hint for `/postembed` is lengthy because it relists the arguments for the alias, and lists the command without arguments as "alternative syntax" without acknowledging that `<link>` is optional. Something like
```
Usage: /postembed [<link>] [<message>] (Alias: /pe) (Valid links: Twitch streams, VODs, clips, Youtube, Rumble)
```
addresses this.

To take a step back, it's a relatively complex command whose behavior can't be conveyed in a single line. It might be better to explain in more detail what it does if the user uses it incorrectly, but that's a problem for another day.

2023-02-15 21:01 UTC, 11k requested changes

2023-02-15 21:01 UTC, 11k commented on assets/chat/js/chat.js
> +      location.href = `${noEmbedUrl}${hashLink}`;
I did some testing and I'm fairly certain we can simplify all this to
```
location.hash = this.hashLinkConverter.convert(parts[0]);
```

2023-02-15 21:01 UTC, 11k commented on assets/chat/js/chat.js
> +      this.source.send('MSG', { data: `${hashLink} ${moreMsg}` });
`slice()` returns an empty array if the first argument is beyond the array's length, so you can simplify all this to
```suggestion
      this.source.send('MSG', { data: `${hashLink} ${parts.slice(1).join(' ')}` });
```

2023-02-15 21:09 UTC, Fritz-02 commented on assets/chat/js/chat.js
> +      location.href = `${noEmbedUrl}${hashLink}`;
Nice, works for me and looks cleaner. Done 👍

2023-02-15 21:39 UTC, 11k approved these changes

2023-02-15 21:40 UTC, merged