Better subscription and donation messages
destinygg/chat-gui pull request #181
Opened 2023-03-08 14:23 UTC by vyneer

Adds prettier sub and dono messages.

Donos are split into 5 tiers (5-10, 10-25, 25-50, 50-100, >100) with hard-coded borders of different colors, the first 4 roughly mirroring the default DGG sub colors, and the last one being just red. Each tier also has its own cute icon (icons were downloaded from flaticon.com, would need to make an attribution page).

![image](https://user-images.githubusercontent.com/41237021/223737272-bace7b5a-4d6a-446c-8439-0043c97fbac1.png)

Subs get the border color dynamically from the flair/sub colors, including the rainbow-colored tier 5 (not animated though). Just like donos, subs have their own icons for each action: regular sub, sub gift and sub mass gift.

![image](https://user-images.githubusercontent.com/41237021/223737306-6200a039-a490-4dac-badf-393bdfe90e3e.png)
![image](https://user-images.githubusercontent.com/41237021/223737343-cf1034e6-76fb-4367-b0fc-2839b3a8ef5f.png)

In on-stream chat the messages look slightly differently, since (imo) the full round borders don't look as nice overlayed on top of other stuff, so I went with just a tier colored line on the left.

![image](https://user-images.githubusercontent.com/41237021/223737866-a7e537ff-08f7-42f0-9860-f8bdb77d7b48.png)
![image](https://user-images.githubusercontent.com/41237021/223737925-553e0fcb-6d1b-4a96-94fe-5657ad9060f0.png)

Needs https://github.com/destinygg/chat-private/pull/9 and https://github.com/destinygg/website-private/pull/102 to work.

2023-05-01 23:22 UTC, 11k requested changes

2023-05-01 23:22 UTC, 11k commented on assets/chat/js/messages/subscriptions/ChatSubscriptionMessage.js
> +    }
I think switching on `MessageTypes` here is child class logic leaking into the parent class. A better approach is to define `templateID` as a constructor parameter and assign it a value in each subclass.

2023-05-01 23:22 UTC, 11k commented on assets/chat/js/messages/subscriptions/ChatSubscriptionMessage.js
> +    if (this.giftee) attr['data-giftee'] = this.giftee.toLowerCase();
This seems like the wrong place for this assignment considering `giftee` is only relevant for gifted subs. Is there any particular reason you're doing this here?

2023-05-02 12:54 UTC, vyneer commented on assets/chat/js/messages/subscriptions/ChatSubscriptionMessage.js
> +    if (this.giftee) attr['data-giftee'] = this.giftee.toLowerCase();
No reason, I think I just missed this when splitting the classes up, thank you!

2023-05-17 08:17 UTC, 11k approved these changes

2023-05-17 08:17 UTC, merged