Improved whisper menu
destinygg/chat-gui pull request #227
Opened 2023-04-18 06:29 UTC by Mitchdev

Show all your whispers and indicate if the user is online

![image](https://user-images.githubusercontent.com/13901269/232690079-2908d7cd-a00e-4a15-8790-f357e174ce8d.png)

2023-09-06 18:49 UTC, 11k requested changes
I'd like to finally take a look at this. 😅 Would you mind merging in master and fixing any merge conflicts?

2023-09-11 05:57 UTC, Mitchdev commented
For some reason the prettier commit didn't merge when I merged the master branch in.

2024-04-17 23:26 UTC, 11k requested changes
Would you mind fixing the merge conflicts, and humanizing the date next to each conversation (e.g., "a month ago")? You can give the date a title so that it displays a local time in a localized format on hover.

2024-05-29 19:48 UTC, 11k requested changes

2024-05-29 19:48 UTC, 11k commented on assets/chat/js/menus/ChatWhisperUsers.js
> +        )}">${time.fromNow()}</span>
Would you mind using code tags to make this a little more readable? It's a dependency we added sometime after this PR.

2024-05-29 19:48 UTC, 11k commented on assets/chat/css/style.scss
> +        -webkit-border-radius: 7.5px;
Are vendor prefixes still necessary here?

2024-05-29 19:48 UTC, 11k commented on assets/chat/css/style.scss
> +  .section {
I find this CSS challenging to read and I think it's a combination of there being no newlines before each nested ruleset and excessive nesting. For instance, you don't need this level of specificity to select `.unread`.
```
#chat-whisper-users .section .user-entry .right .unread {
}
```
I think the issue is you're trying to make the nesting in your CSS reflect the nesting in your markup. Besides readability, you can also run into situations where you have to rely on `!important` more often to override styles.

2026-08-10 18:17 UTC, 11k commented
Implemented in #871 with related migration/API PRs in website.

2026-08-10 18:17 UTC, closed without merging