DGGTweaker Features - Link Hitbox Scaling, RustleSearch button and Lucide Icons
destinygg/chat-gui pull request #553
Opened 2024-11-12 16:28 UTC by AlexDavies8

After Cake mentioned it in the discord I figured I'd port the chat related stuff from [my extension](https://github.com/AlexDavies8/dgg-tweaker) to the main chat codebase.
Here's a list of the changes:
- Added a new chat setting to increase the clickable area of a link (bigger 'hitbox')
- Added button to the user info right click menu that directly links to rustlesearch.dev
- Basic support for numeric fields in chat settings (in the future could put maxlines in the UI instead of needing a command)
- Icons have been swapped out for Lucide icons to match with the main site redesign
- Button tooltips have been changed from using the title attribute to using tippy, and the tippy style is prettier

![New Look](https://github.com/user-attachments/assets/05c940a9-eb95-4400-80d0-e25b58a6eabc)

2024-11-14 21:33 UTC, 11k requested changes
For your link scaling setting, (1) the way it's presented in the settings menu is confusing to the average user, (2) there's too much flexibility in allowing a custom multiplier considering only a few values are actually sane, and (3) the scaling seems to apply upward more than it does downward.

We can work to address these issues, but I don't think it's worth it because difficulty with clicking links isn't a big problem. The setting works perfectly as a customization for interested users to apply via an extension like yours.

Other than that, would you mind updating the embed link icon to Lucide as well? It's the TV that's displayed alongside an embeddable URL and is defined inline in `UrlFormatter.js`.

2024-11-14 21:33 UTC, 11k commented on assets/chat/js/menus/ChatUserMenu.js
> +      `<div class="user-entry" data-username="${user.username}" data-user-id="${user.id}"><span class="user ${features}">${label}</span><div class="user-actions"><i class="mention-nick" title="Mentio
Why not make these Tippy tooltips as well?

2024-11-14 21:33 UTC, 11k commented on assets/chat/img/icon-open-in-new.svg
I don't think this icon is used anywhere. If so, it's safe to delete.

2024-11-14 21:33 UTC, 11k commented on assets/chat/img/icon-favorite-fill.svg
It seems new favorite emote icons are clipped. Would you mind fixing this?

2024-11-14 22:42 UTC, AlexDavies8 commented on assets/chat/js/menus/ChatUserMenu.js
> +      `<div class="user-entry" data-username="${user.username}" data-user-id="${user.id}"><span class="user ${features}">${label}</span><div class="user-actions"><i class="mention-nick" title="Mentio
I tried this but they didn't get registered properly. It should now work with tippy, as I'm manually registering them with tippy.

2024-11-14 22:42 UTC, AlexDavies8 commented on assets/chat/img/icon-open-in-new.svg
Done 👍

2024-11-14 22:43 UTC, AlexDavies8 commented on assets/chat/img/icon-favorite-fill.svg
Done 👍

2024-11-14 22:44 UTC, AlexDavies8 commented
I've reverted the link hitbox changes, changed the embed icon and addressed other mentioned changes.

2024-11-16 00:22 UTC, 11k approved these changes

2024-11-16 06:36 UTC, merged